FROM nvcr.io/nvidia/tensorflow:24.01-tf2-py3

RUN pip install quart pandas numpy matplotlib seaborn scikit-learn ipykernel asyncio-redis redis Werkzeug nest_asyncio Flask-Cors asyncio hypercorn pytest-asyncio websocket-client