services:
  quart_app:
    restart: always
    build:
      context: .
      dockerfile: quartapp/Dockerfile
    container_name: quart_app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - quart_app_data:/home/quart/instance/pcaps

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    command: redis-server --dir /data --save 60 1 --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
          test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
          interval: 2s
          timeout: 1m30s
          retries: 5
          start_period: 5s


  # redis:
  #  image: redis:latest
  #  container_name: redis
  #  volumes:
  #    - redis_data:/data  # Mount the volume for data persistence

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - quart_app

volumes:
  quart_app_data:
    external: true
  redis_data:
    external: true
  caddy_data:
    external: true
  caddy_config:
    external: true
