package com.bcl.netifidash;

import com.codename1.system.Lifecycle;
import com.codename1.ui.*;
import com.bcl.netifidash.ui.UI;


/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class NetiFiDash extends Lifecycle {
    @Override
    public void runApp() {
        Toolbar.setGlobalToolbar(true);
        UI ui = new UI();
        ui.splashScreen();
    }
}
