package com.bcl.netifidash;

import com.codename1.system.Lifecycle;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;
import com.codename1.io.*;
import com.codename1.ui.plaf.*;
import com.bcl.netifidash.util.BackendUtil;
import com.codename1.ui.util.UITimer;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class NetiFiDash extends Lifecycle {
    @Override
    public void runApp() {
        Toolbar.setGlobalToolbar(true);
        splashScreen();
    }

    private void hello() {
        Dialog.show("Hello Codename One", "Welcome to Codename One", "OK", null);
    }

    private void auth(){
        BackendUtil backendUtil = new BackendUtil();
        backendUtil.auth();
    }

    private void splashScreen(){

        Form main = new Form("", BoxLayout.y());
        TextArea name = new TextArea();
        name.setText("Welcome to NetiFiDash");
        main.add(name);
        main.show();

        new UITimer(() -> {
            Form mainApp = home();
            mainApp.show();
        }).schedule(5000, false, main);
    }

    private Form home(){
        Form home = new Form("Home", BoxLayout.y());
        Button helloButton = new Button("Hello World");
        Button socketTest = new Button("Send message to backend");
        TextField eventType = new TextField("Enter Event Type");
        TextField eventMessage = new TextField("Enter Event Message");
        TextField socketHost = new TextField("Enter Socket IP/Hostname");
        TextField socketPort = new TextField("Enter Socket Port");
        home.add(socketHost);
        home.add(socketPort);
        home.add(eventType);
        home.add(eventMessage);

        helloButton.addActionListener(e -> hello());
        socketTest.addActionListener(e -> nocDash());
        home.add(helloButton);
        home.add(socketTest);
        setMenu(home);
        return home;
    }

    private void nocDash(){
        Form noc = new Form("Dashboard", BoxLayout.y());
        setMenu(noc);
        noc.show();
    }

    private void net_dev_mgmt(){
        Form netDev = new Form("Network Devices", BoxLayout.y());
        setMenu(netDev);
        netDev.show();
    }

    private void client_mgmt(){
        Form usrDev = new Form("Client Devices", BoxLayout.y());
        setMenu(usrDev);
        usrDev.show();

    }

    private void setMenu(Form form){

        form.getToolbar().addMaterialCommandToSideMenu("Home",
                FontImage.MATERIAL_CHECK_CIRCLE_OUTLINE, 6, e -> home().show());
        form.getToolbar().addMaterialCommandToSideMenu("Dashboard",
                FontImage.MATERIAL_CHECK_CIRCLE_OUTLINE, 6, e -> nocDash());
        form.getToolbar().addMaterialCommandToSideMenu("Network Devices",
                FontImage.MATERIAL_CHECK_CIRCLE_OUTLINE, 6, e -> net_dev_mgmt());
        form.getToolbar().addMaterialCommandToSideMenu("Client Devices",
                FontImage.MATERIAL_CHECK_CIRCLE_OUTLINE, 6, e -> client_mgmt());

    }



}
